"""CLI regressions against fixtures generated by AssetExportTest."""

import math
from pathlib import Path
import struct
import subprocess
import sys
import tempfile
import unittest
import xml.etree.ElementTree as ET
import zipfile


ROOT = Path(__file__).resolve().parents[1]
FIXTURES = ROOT / "core/build/export-fixtures"
EXTENSIONS = ("stl", "3mf", "step", "iges", "dxf", "svg")


class ExportVerifierTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        missing = [suffix for suffix in EXTENSIONS if not (FIXTURES / f"spur.{suffix}").is_file()]
        if missing:
            raise AssertionError(f"Run :core:test --tests '*AssetExportTest*' first; missing {missing}")

    def run_verifier(self, path, *arguments):
        return subprocess.run(
            [sys.executable, str(ROOT / "tools/verify_export.py"), str(path), *arguments],
            capture_output=True, text=True, encoding="utf-8", timeout=30, check=False,
        )

    def assert_rejected(self, path, *arguments):
        result = self.run_verifier(path, *arguments)
        self.assertEqual(1, result.returncode, result.stdout + result.stderr)
        self.assertIn("[FEL]", result.stdout)
        self.assertNotIn("Traceback", result.stderr)

    def test_six_writer_outputs_pass_cli(self):
        for suffix in EXTENSIONS:
            with self.subTest(format=suffix):
                arguments = ("--expect-diameter", "22", "--expect-triangles", "5632") if suffix == "stl" else ()
                result = self.run_verifier(FIXTURES / f"spur.{suffix}", *arguments)
                self.assertEqual(0, result.returncode, result.stdout + result.stderr)
                self.assertNotIn("[VARN]", result.stdout)

    def test_each_format_rejects_malformed_file(self):
        with tempfile.TemporaryDirectory() as directory:
            for suffix in EXTENSIONS:
                with self.subTest(format=suffix):
                    data = (FIXTURES / f"spur.{suffix}").read_bytes()
                    malformed = {
                        "stl": data[:-1],
                        "3mf": b"not a ZIP archive",
                        "step": data.replace(b"END-ISO-10303-21;", b""),
                        "iges": b"x" * 81 + b"\n",
                        "dxf": data + b"\n999\n",
                        "svg": data.replace(b"</svg>", b""),
                    }[suffix]
                    path = Path(directory) / f"bad.{suffix}"
                    path.write_bytes(malformed)
                    self.assert_rejected(path)

    def test_empty_files_fail_for_all_formats(self):
        with tempfile.TemporaryDirectory() as directory:
            for suffix in EXTENSIONS:
                with self.subTest(format=suffix):
                    path = Path(directory) / f"empty.{suffix}"
                    path.write_bytes(b"")
                    self.assert_rejected(path)

    def test_wrong_diameter_fails(self):
        self.assert_rejected(FIXTURES / "spur.stl", "--expect-diameter", "558.8")

    def test_wrong_triangle_expectation_fails(self):
        self.assert_rejected(FIXTURES / "spur.stl", "--expect-triangles", "1")

    def test_step_jvm_array_reference_fails(self):
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "array-reference.step"
            path.write_bytes(b"ISO-10303-21;\nDATA;\n#2=LINE('',#[I@123abc[a],#1);\nENDSEC;\nEND-ISO-10303-21;\n")
            self.assert_rejected(path)

    def test_stl_nonfinite_vertex_fails(self):
        with tempfile.TemporaryDirectory() as directory:
            for value in (math.nan, math.inf):
                with self.subTest(value=value):
                    data = bytearray((FIXTURES / "spur.stl").read_bytes())
                    struct.pack_into("<f", data, 96, value)
                    path = Path(directory) / "nonfinite.stl"
                    path.write_bytes(data)
                    self.assert_rejected(path)

    def test_stl_incorrect_declared_count_fails(self):
        data = bytearray((FIXTURES / "spur.stl").read_bytes())
        struct.pack_into("<I", data, 80, 1)
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "count.stl"
            path.write_bytes(data)
            self.assert_rejected(path)

    def test_3mf_missing_opc_entries_fails(self):
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "missing.3mf"
            with zipfile.ZipFile(path, "w") as archive:
                archive.writestr("3D/3dmodel.model", "<model/>")
            self.assert_rejected(path)

    def test_3mf_geometry_dimensions_and_units(self):
        with zipfile.ZipFile(FIXTURES / "spur.3mf") as archive:
            model = ET.fromstring(archive.read("3D/3dmodel.model"))
        self.assertEqual("millimeter", model.attrib["unit"])
        namespace = {"m": "http://schemas.microsoft.com/3dmanufacturing/core/2015/02"}
        vertices = [tuple(float(vertex.attrib[axis]) for axis in ("x", "y", "z"))
                    for vertex in model.findall(".//m:vertex", namespace)]
        self.assertTrue(vertices)
        for axis, expected in enumerate((22.0, 22.0, 6.0)):
            dimension = max(vertex[axis] for vertex in vertices) - min(vertex[axis] for vertex in vertices)
            self.assertAlmostEqual(expected, dimension, delta=0.05)
        self.assertEqual(5632, len(model.findall(".//m:triangle", namespace)))


if __name__ == "__main__":
    unittest.main()